### ISSUE TITLE
Add listener code to purl-fetcher

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/purl-fetcher#66]
- [ ] implement listener process using gem (in #104)
- [ ] integrate listener process management with capistrano (in #104)
- [ ] develop entry point for listener to make index changes (in #104)
- [ ] document administrative use (where should this doc live?)
- [ ] implement changes to the `publish` robot (in #103)

Also see #61

**Comment by drh-stanford** [comment]
@eefahy and I have implemented the purl-fetcher portion of following algorithm in #104. It's based on Lynn's idea to have the publish robot create a druid file (ala the `.deletes` folder) after a successful publish.

The algorithm is as follows (comments on where it should live?).

- `publish` robot (see https://github.com/sul-dlss/purl-fetcher/issues/103)
  - create `/purl/document_cache/.recent_changes/aa111bb2222` file via touch _after_ successful publish
  - also ensures that `/purl/document_cache/.deletes/aa111bb2222` is removed

- `purl-fetcher`
  - mount `/purl/document_cache` as `rw`
  - listener watches `/purl/document_cache/.recent_changes` directory for events, then on event:
    - logs that the listener process is active
    - rename `aa111bb2222` to `aa111bb2222.lock`
    - save to `Purl` model, and logs (to file and Honeybadger) any exceptions (then continues)
    - delete `aa111bb2222.lock`
  - when listener boots
    - it checks to see when it was last active
    - then runs a `find:all[mins_ago]` task
  - `/is_it_working` reports on the listener process (whether it's running)

- if something goes very wrong with the listener then we can clean out the `.recent_changes` directory like so, and run `find:all` again:
  - `find .recent_changes -mtime 14 -type f \! -name '*.lock' | xargs rm`
